Repository SirriRyisa/cansaCare, pull requests merged in 2023-03, with the labels that each got.

#3 Adding thread part ==> Georges
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eagle/cansacare/HomeActivity2.java
  app/src/main/java/com/eagle/cansacare/SocialBanner.java
  app/src/main/java/com/eagle/cansacare/comment/Comment.java
  app/src/main/java/com/eagle/cansacare/comment/CommentAdapter.java
  app/src/main/java/com/eagle/cansacare/getStartedAccountsCreation/CreateAccount.java
  app/src/main/java/com/eagle/cansacare/getStartedAccountsCreation/GetStarted.java
  app/src/main/java/com/eagle/cansacare/getStartedAccountsCreation/Login.java
  app/src/main/java/com/eagle/cansacare/getStartedAccountsCreation/UserModel.java
  app/src/main/java/com/eagle/cansacare/onboardingAndSplash/MainActivity.java
  app/src/main/java/com/eagle/cansacare/onboardingAndSplash/SplashScreen.java
  app/src/main/java/com/eagle/cansacare/onboardingAndSplash/ViewPagerAdapter.java
  app/src/main/java/com/eagle/cansacare/post/Post.java
  app/src/main/java/com/eagle/cansacare/post/PostAdapter.java
  app/src/main/java/com/eagle/cansacare/post/PostDetailActivity.java
  app/src/main/java/com/eagle/cansacare/profileSetUp/ProfileSetup.java
  app/src/main/java/com/eagle/cansacare/profileSetUp/ProfileSetupDetails.java
  app/src/main/java/com/eagle/cansacare/ui/dashboard/DashboardFragment.java
  app/src/main/java/com/eagle/cansacare/ui/home/HomeFragment.java
  app/src/main/res/drawable/back_ic.xml
  app/src/main/res/drawable/blog_physioterapy_image.xml
  app/src/main/res/drawable/circle_ic.xml
  app/src/main/res/drawable/hashtag_ic.xml
  app/src/main/res/layout/activity_create_account.xml
  app/src/main/res/layout/activity_login_layout.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile_setup.xml
  app/src/main/res/layout/activity_profile_setup_details.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/comment_row.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/post_description.xml
  app/src/main/res/layout/post_item_layout.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#4 Add new post on main thread
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eagle/cansacare/CreateNewThreadPost.java
  app/src/main/java/com/eagle/cansacare/ThreadAdapter.java
  app/src/main/java/com/eagle/cansacare/ThreadDisplay.java
  app/src/main/java/com/eagle/cansacare/ThreadPost.java
  app/src/main/java/com/eagle/cansacare/ui/dashboard/DashboardFragment.java
  app/src/main/res/drawable/add_post_ic.xml
  app/src/main/res/drawable/circle_ic.xml
  app/src/main/res/drawable/comment_ic.xml
  app/src/main/res/drawable/like_ic.xml
  app/src/main/res/drawable/search_ic.xml
  app/src/main/res/layout/activity_create_new_thread_post.xml
  app/src/main/res/layout/activity_thread_display.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/post_thread_card.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#9 Fixing the display of RecyclerView
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eagle/cansacare/CreateNewThreadPost.java
  app/src/main/java/com/eagle/cansacare/HomeActivity2.java
  app/src/main/java/com/eagle/cansacare/ThreadAdapter.java
  app/src/main/java/com/eagle/cansacare/ThreadDisplay.java
  app/src/main/java/com/eagle/cansacare/ThreadPost.java
  app/src/main/java/com/eagle/cansacare/ui/dashboard/DashboardFragment.java
  app/src/main/res/drawable/message_navbar.xml
  app/src/main/res/drawable/personal_profile.xml
  app/src/main/res/layout/activity_thread_display.xml
  app/src/main/res/menu/bottom_nav_menu.xml
Labels: bug, good first issue

#13 Booking merge
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eagle/cansacare/AppointmentFragment.java
  app/src/main/java/com/eagle/cansacare/ProfileSetup.java
  app/src/main/java/com/eagle/cansacare/ServiceBooking.java
  app/src/main/java/com/eagle/cansacare/ServiceDetails.java
  app/src/main/java/com/eagle/cansacare/Services.java
  app/src/main/java/com/eagle/cansacare/ServicesAdapter.java
  app/src/main/java/com/eagle/cansacare/ServicesFragment.java
  app/src/main/java/com/eagle/cansacare/ServicesList.java
  app/src/main/java/com/eagle/cansacare/getStartedAccountsCreation/CreateAccount.java
  app/src/main/java/com/eagle/cansacare/getStartedAccountsCreation/UserModel.java
  app/src/main/java/com/eagle/cansacare/ui/dashboard/DashboardFragment.java
  app/src/main/res/drawable/ic_colored_notifications.xml
  app/src/main/res/drawable/ic_schedule.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/iconmonstr_heart_thin.xml
  app/src/main/res/drawable/physiotherapy.xml
  app/src/main/res/drawable/round_back_white.xml
  app/src/main/res/drawable/rounded_tab_colour.xml
  app/src/main/res/layout/activity_login_layout.xml
  app/src/main/res/layout/activity_main_services_tabs.xml
  app/src/main/res/layout/activity_profile_setup_details.xml
  app/src/main/res/layout/activity_service_booking.xml
  app/src/main/res/layout/activity_service_details.xml
  app/src/main/res/layout/activity_services.xml
  app/src/main/res/layout/fragment_appointment.xml
  app/src/main/res/layout/fragment_services.xml
  app/src/main/res/layout/post_description.xml
  app/src/main/res/layout/post_item_layout.xml
  app/src/main/res/layout/service_item_card.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#18 booking fragment
  app/src/main/java/com/eagle/cansacare/getStartedAccountsCreation/CreateAccount.java
  app/src/main/java/com/eagle/cansacare/getStartedAccountsCreation/UserModel.java
  app/src/main/java/com/eagle/cansacare/ui/dashboard/DashboardFragment.java
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/strings.xml
Labels: good first issue

#21 Create a new booking way
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eagle/cansacare/Appointment.java
  app/src/main/java/com/eagle/cansacare/BookingServiceAppointment.java
  app/src/main/java/com/eagle/cansacare/ConfirmAppointment.java
  app/src/main/java/com/eagle/cansacare/ServicesAdapter.java
  app/src/main/java/com/eagle/cansacare/onboardingAndSplash/SplashScreen.java
  app/src/main/java/com/eagle/cansacare/ui/bookings/BookingFragment.java
  app/src/main/res/drawable/button_bg_orange.xml
  app/src/main/res/drawable/null_radio_button.xml
  app/src/main/res/drawable/radio_not_selected.xml
  app/src/main/res/drawable/radio_selected.xml
  app/src/main/res/drawable/radio_selector.xml
  app/src/main/res/drawable/radio_text_selector.xml
  app/src/main/res/layout/activity_booking_service_appointment.xml
  app/src/main/res/layout/activity_confirm_appointment.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#24 Update appointment model
  app/src/main/java/com/eagle/cansacare/Appointment.java
  app/src/main/java/com/eagle/cansacare/BookingServiceAppointment.java
  app/src/main/java/com/eagle/cansacare/ServicesFragment.java
  app/src/main/java/com/eagle/cansacare/getStartedAccountsCreation/CreateAccount.java
  app/src/main/java/com/eagle/cansacare/thread/CreateNewThreadPost.java
Labels: enhancement

#26 Update appointment model
  app/src/main/java/com/eagle/cansacare/Appointment.java
  app/src/main/java/com/eagle/cansacare/BookingServiceAppointment.java
  app/src/main/java/com/eagle/cansacare/thread/CreateNewThreadPost.java
Labels: enhancement
